export enum SERVER {
  HEROKU = 'HEROKU',
  AWS = 'AWS',
  ALIYUN = 'ALIYUN',
  ORACLE = 'ORACLE',
  LOCALHOST = 'LOCALHOST',
}

export enum PAYMENT_TYPE {
  WECHAT = 'WECHAT',
  ALIPAY = 'ALIPAY',
  STRIPE_ONLINE = 'STRIPE_ONLINE',
  STRIPE_TEST = 'STRIPE_TEST',
}
